dist: trusty
language: python
jobs:
  include:
  - python: "3.2"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
install:
- python3 -m pip install pydiatra $pyflakes
script:
- ./chemiscripts '3(NH4)2S + Sb2S5 -> 6NH4+ + 2SbS4 3+'
- python3 -m pydiatra .
- python3 -m pyflakes .
matrix:
  include:
  - python: null
    before_install: []
    install:
    - pip install restructuredtext-lint pygments
    - pip install html5validator
    script:
    - restructuredtext-lint --encoding=UTF-8 README
    - html5validator --also-check-css *.html

# vim:ts=2 sts=2 sw=2 et
